language: node_js
node_js: 12.13.0



os:
- windows

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then  npm install --global node-gyp@latest; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm i electron-rebuild --save-dev; fi
  - npm i

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run electron:release --win; fi


# only run this script on pull requests and merges into 
# the 'master' and 'qa' branches
branches:
  only:
  - main